#!/bin/sh -e

# exit if the resolvconf package is installed
[ -x /sbin/resolvconf ] && exit 0

# follow any symlink to find the real file
if [ -e /etc/resolv.conf ]; then
  REALRESOLVCONF=$(readlink --canonicalize /etc/resolv.conf)
else
  REALRESOLVCONF=/etc/resolv.conf
fi

# if an old resolv.conf file exists, restore it
if [ -e $REALRESOLVCONF.pppd-backup ]; then
  mv -f $REALRESOLVCONF.pppd-backup $REALRESOLVCONF

  # restart nscd because resolv.conf has changed
  if [ -e /var/run/nscd.pid ]; then
    /etc/init.d/nscd restart || true
  fi
fi

exit 0

# This script undos the effect of /etc/ppp/ip-up.d/0000usepeerdns. We use 
# /etc/ppp/ip-up.d/vyatta-usepeerdns to update resolv.conf. Also on link 
# down /etc/ppp/ip-down.d/0000usepeerdns will have no effect. We update 
# resolv.conf on linkdown with /etc/ppp/ip-down.d/vyatta-usepeerdns 
