#!/usr/bin/perl

use strict;
use lib "/opt/vyatta/share/perl5/";
use XorpConfigParser;

my $orig_cfg = shift;
exit 1 if (!defined($orig_cfg));

my $xcp = new XorpConfigParser();
$xcp->parse($orig_cfg);
my $root_node = $xcp->get_node([]);
my $root_children = $root_node->{'children'};
my $cluster = $xcp->find_child($root_children, 'cluster');
if (defined($cluster)) {
  $xcp->comment_out_child($root_children, 'cluster',
                          'Cluster is not supported');
}

my $tmpfile = "/tmp/vyatta_migrate_cluster.$$";
open(TMPFILE, ">$tmpfile") or exit 1;
select TMPFILE;
      
$xcp->output(0); 
        
close TMPFILE;
my $ret = system("mv $tmpfile $orig_cfg");
exit 1 if ($ret >> 8);
      
exit 0; 

