#!/bin/sh -e

if [ "$1" = "configure" ]; then
    SEQFILE=/var/spool/cron/atjobs/.SEQ
    if [ ! -f $SEQFILE ]; then
	echo 0 > $SEQFILE
	chmod 600 $SEQFILE
	chown daemon:daemon $SEQFILE
    fi
fi

# Automatically added by dh_installinit
if [ -x "/etc/init.d/atd" ]; then
	update-rc.d atd defaults 89 11 >/dev/null
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d atd start || exit $?
	else
		/etc/init.d/atd start || exit $?
	fi
fi
# End automatically added section

