#!/bin/sh
set -e

# Remove the cache file so that the directory can be deleted.
#
if [ "$1" = "remove" -o "$1" = "purge" ]; then
    rm -f /var/cache/ddclient/ddclient.cache
fi

# Automatically added by dh_installinit
if [ -x "/etc/init.d/ddclient" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d ddclient stop || exit $?
	else
		/etc/init.d/ddclient stop || exit $?
	fi
fi
# End automatically added section


exit 0

