#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
    rm -f /etc/ipvsadm.rules
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d ipvsadm remove >/dev/null || exit $?
fi
# End automatically added section
# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
	
