#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
	adduser --system --quiet --group --no-create-home ntp || :
	chown -R ntp:ntp /var/lib/ntp /var/log/ntpstats
fi

installinit_error() {
	exit $?
}

# Automatically added by dh_installinit
if [ -x "/etc/init.d/ntp" ]; then
	update-rc.d ntp start 23 2 3 4 5 . >/dev/null
	invoke-rc.d ntp start || installinit_error
fi
# End automatically added section

