#!/bin/bash

prefix=/opt/vyatta
exec_prefix=${prefix}
bindir=${exec_prefix}/bin

# add symlinks for sudo
ln -sf /opt/vyatta/bin/vyatta-show-interfaces.pl ${bindir}/sudo-users/vyatta-show-interfaces.pl
ln -sf /opt/vyatta/sbin/vyatta-interfaces.pl ${bindir}/sudo-users/vyatta-interfaces.pl

# rm symlink for sendmail that was added by ssmtp package
rm -f /usr/sbin/sendmail

# handle renamed file (not automatically deleted since it was "conffile")
rm -f /etc/bash_completion.d/10vyatta-op

