#! /usr/bin/perl

# Starting Mendocino, content-inspection provided the ability to specify
# different "outputs".  Add "output local" as default.

use strict;
use warnings;

use lib "/opt/vyatta/share/perl5/";
use XorpConfigParser;
use File::Copy;

my $orig_cfg = shift;
exit 1 unless $orig_cfg;

my $xcp = new XorpConfigParser();
$xcp->parse($orig_cfg);

my $ci = $xcp->get_node(['content-inspection']);
exit 0 unless $ci; # content-inspection not configured

my $loc = $xcp->create_node(['content-inspection', 'ips', 'log', 'local']);
die "Can't make content-inspection ips log local\n" unless $loc;

my $tmpname = "/tmp/vyatta_migrate_content_inspection.$$";
open (my $tmp, '>', $tmpname)
    or die "Can't open: $tmpname: $!";

select $tmp;
$xcp->output(0);
select STDOUT;
close $tmp;

move($tmpname, $orig_cfg)
    or die "Move $tmpname to $orig_cfg failed: $!";

exit 0;
